/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emprego.view;

import emprego.Banco;
import emprego.model.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gcamargo
 */
public class Cadastro extends javax.swing.JFrame {

    Usuario usuariologado = new Usuario();
    private int clicado = 0;
    private boolean isProfissional = false;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Empre GO - Cadastro");
    }

    public Cadastro(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Empre GO - Cadastro");
        this.usuariologado = usuario;
        jTextFieldCadastroNome.setText(usuariologado.getNome());
        jTextFieldDataNascimento.setText(usuariologado.getData_Nascimento());
        jTextFieldCadastroEmail.setText(usuariologado.getEmail());
        jTextFieldCadastroEndereco.setText(usuariologado.getEndereco());
        jTextFieldCadastroTelefone.setText(String.valueOf(usuariologado.getTelefone()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroNome = new javax.swing.JLabel();
        jTextFieldCadastroNome = new javax.swing.JTextField();
        jLabelCadastroEmail = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jLabelCadastroEndereco = new javax.swing.JLabel();
        jTextFieldCadastroEndereco = new javax.swing.JTextField();
        jLabelCadastroTelefone = new javax.swing.JLabel();
        jLabelCadastroProfissao = new javax.swing.JLabel();
        jTextFieldCadastroProfissao = new javax.swing.JTextField();
        jLabelCadastroExperienciaDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCadastroExperienciaDescricao = new javax.swing.JTextArea();
        jButtonCompletarVoltar = new javax.swing.JButton();
        jButtonCompletarCadastro = new javax.swing.JButton();
        jTextFieldCadastroTelefone = new javax.swing.JTextField();
        jLabelCompletarCadastro = new javax.swing.JLabel();
        jCheckBoxSolicitacoes = new javax.swing.JCheckBox();
        jLabelDataNascimento = new javax.swing.JLabel();
        jTextFieldDataNascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabelCadastroNome.setText("Nome:");

        jLabelCadastroEmail.setText("Email:");

        jLabelCadastroEndereco.setText("* Endereço:");

        jLabelCadastroTelefone.setText("Telefone:");

        jLabelCadastroProfissao.setText("* Profissão:");

        jLabelCadastroExperienciaDescricao.setText("Conte um pouco da sua última experiência profissional:");

        jTextAreaCadastroExperienciaDescricao.setColumns(20);
        jTextAreaCadastroExperienciaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCadastroExperienciaDescricao);

        jButtonCompletarVoltar.setText("Voltar");
        jButtonCompletarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompletarVoltarActionPerformed(evt);
            }
        });

        jButtonCompletarCadastro.setText("Completar");
        jButtonCompletarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompletarCadastroActionPerformed(evt);
            }
        });

        jTextFieldCadastroTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCadastroTelefoneKeyTyped(evt);
            }
        });

        jLabelCompletarCadastro.setText("Complete seu Cadastro");

        jCheckBoxSolicitacoes.setText("Desejo estar disponível para contratação");
        jCheckBoxSolicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSolicitacoesActionPerformed(evt);
            }
        });

        jLabelDataNascimento.setText("Data de nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabelCompletarCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCompletarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCompletarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBoxSolicitacoes)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCadastroEndereco)
                                            .addComponent(jLabelCadastroEmail)
                                            .addComponent(jLabelCadastroNome))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelDataNascimento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldDataNascimento))
                                            .addComponent(jTextFieldCadastroEmail)
                                            .addComponent(jTextFieldCadastroEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCadastroNome)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabelCadastroExperienciaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCadastroProfissao)
                                    .addComponent(jLabelCadastroTelefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCadastroProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelCompletarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSolicitacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroEmail)
                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroEndereco)
                    .addComponent(jTextFieldCadastroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroTelefone)
                    .addComponent(jTextFieldCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroProfissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCadastroExperienciaDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCompletarVoltar)
                    .addComponent(jButtonCompletarCadastro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompletarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompletarVoltarActionPerformed
        Inicio voltar = new Inicio();
        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCompletarVoltarActionPerformed

    private void jButtonCompletarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompletarCadastroActionPerformed
        
       if(isProfissional == true){
           try {
               Banco salvarUsuario = new Banco();
               String nome = jTextFieldCadastroNome.getText();
               String dataNascimento = jTextFieldDataNascimento.getText();
               String email = jTextFieldCadastroEmail.getText();
               String endereco = jTextFieldCadastroEndereco.getText();
               int telefone = Integer.valueOf(jTextFieldCadastroTelefone.getText());
              if(salvarUsuario.completarCadastroUsuario(nome, dataNascimento, email, endereco, telefone, usuariologado.getIdUsuario())){
                  JOptionPane.showMessageDialog(null, "Cadastro Completo.");
                  Inicio voltar = new Inicio();
                  voltar.setVisible(true);
                  this.dispose();
              }else{
                  JOptionPane.showMessageDialog(null,"Não foi possível completar teu cadastro.");
              }
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex+"\n\nVerifique as configurações do serv idor Mysql");
           }
       }else{
           try {
               String nome = jTextFieldCadastroNome.getText();
               String dataNascimento = jTextFieldDataNascimento.getText();
               String email = jTextFieldCadastroEmail.getText();
               String endereco = jTextFieldCadastroEndereco.getText();
               int telefone = Integer.valueOf(jTextFieldCadastroTelefone.getText());
               String profissao = jTextFieldCadastroProfissao.getText();
               String experiencia = jTextAreaCadastroExperienciaDescricao.getText();
               Banco salvarUsuario = new Banco();
               if(salvarUsuario.completarCadastroUsuarioPro(nome, dataNascimento, email, endereco, telefone, usuariologado.getIdUsuario())){
                  if(salvarUsuario.completarCadastroProfissional(experiencia, profissao, usuariologado.getIdUsuario())){
                      JOptionPane.showMessageDialog(null,"Cadastro efetuado com sucesso.");
                      Inicio voltar = new Inicio();
                  voltar.setVisible(true);
                  this.dispose();
                  }else{
                      JOptionPane.showMessageDialog(null,"Não foi possível inserir suas informações profissionais.");
                  }
               }else{
                   JOptionPane.showMessageDialog(null,"Não foi possível completar teu cadastro.");
               }
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
           }
                   }      
          
       
    }//GEN-LAST:event_jButtonCompletarCadastroActionPerformed
//<editor-fold defaultstate="collapsed" desc="Evento jCheckBoxSolicitacoesActionPerformed">

    private void jCheckBoxSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSolicitacoesActionPerformed

        //<editor-fold defaultstate="collapsed" desc="Este método é reponsavel por disponibilizar os campos exclusivos para usuários que queiram se cadastrar como profissional">
        if (clicado != 0) {
            jTextAreaCadastroExperienciaDescricao.setVisible(false);
            jLabelCadastroProfissao.setVisible(false);
            jLabelCadastroExperienciaDescricao.setVisible(false);
            jTextFieldCadastroProfissao.setVisible(false);
            jTextAreaCadastroExperienciaDescricao.setEnabled(false);
            jLabelCadastroProfissao.setEnabled(false);
            jLabelCadastroExperienciaDescricao.setEnabled(false);
            jTextFieldCadastroProfissao.setEnabled(false);
            clicado = 0;
            this.isProfissional = true;
            System.out.println(isProfissional);
        } else {
            jTextAreaCadastroExperienciaDescricao.setVisible(true);
            jLabelCadastroProfissao.setVisible(true);
            jLabelCadastroExperienciaDescricao.setVisible(true);
            jTextFieldCadastroProfissao.setVisible(true);
            jTextAreaCadastroExperienciaDescricao.setEnabled(true);
            jLabelCadastroProfissao.setEnabled(true);
            jLabelCadastroExperienciaDescricao.setEnabled(true);
            jTextFieldCadastroProfissao.setEnabled(true);
            clicado = 1;
            this.isProfissional = false;
        }
        //</editor-fold>

    }//GEN-LAST:event_jCheckBoxSolicitacoesActionPerformed

//</editor-fold>   
    
//<editor-fold defaultstate="collapsed" desc="Evento FormComponentShown">    

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        //<editor-fold defaultstate="collapsed" desc="Desativando Campos exclusivos para Profissional">
        jTextAreaCadastroExperienciaDescricao.setVisible(false);
        jLabelCadastroProfissao.setVisible(false);
        jLabelCadastroExperienciaDescricao.setVisible(false);
        jTextFieldCadastroProfissao.setVisible(false);
        jTextAreaCadastroExperienciaDescricao.setEnabled(false);
        jLabelCadastroProfissao.setEnabled(false);
        jLabelCadastroExperienciaDescricao.setEnabled(false);
        jTextFieldCadastroProfissao.setEnabled(false);
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Pré carregando informações já salvas do usuário">
        jTextFieldCadastroNome.setText(usuariologado.getNome());
        jTextFieldCadastroEmail.setText(usuariologado.getEmail());
        //</editor-fold>

    }//GEN-LAST:event_formComponentShown

//</editor-fold>   
    
//<editor-fold defaultstate="collapsed" desc="Garantindo a inserção de caracteres numéricos">

    private void jTextFieldCadastroTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCadastroTelefoneKeyTyped
        soNumeros(evt, false);
    }//GEN-LAST:event_jTextFieldCadastroTelefoneKeyTyped

//</editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

//<editor-fold defaultstate="collapsed" desc="Método que impossibilita a inserção de caracteres não numéricos através do consume">    
    private void soNumeros(java.awt.event.KeyEvent evt, boolean isDouble) {
        char ch = evt.getKeyChar();
        if (isDouble) {
            if (Character.isDigit(ch) || ch == '.') {

            } else {
                evt.consume();
            }
        } else if (Character.isDigit(ch)) {

        } else {
            evt.consume();
        }
    }
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompletarCadastro;
    private javax.swing.JButton jButtonCompletarVoltar;
    private javax.swing.JCheckBox jCheckBoxSolicitacoes;
    private javax.swing.JLabel jLabelCadastroEmail;
    private javax.swing.JLabel jLabelCadastroEndereco;
    private javax.swing.JLabel jLabelCadastroExperienciaDescricao;
    private javax.swing.JLabel jLabelCadastroNome;
    private javax.swing.JLabel jLabelCadastroProfissao;
    private javax.swing.JLabel jLabelCadastroTelefone;
    private javax.swing.JLabel jLabelCompletarCadastro;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCadastroExperienciaDescricao;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroEndereco;
    private javax.swing.JTextField jTextFieldCadastroNome;
    private javax.swing.JTextField jTextFieldCadastroProfissao;
    private javax.swing.JTextField jTextFieldCadastroTelefone;
    private javax.swing.JTextField jTextFieldDataNascimento;
    // End of variables declaration//GEN-END:variables
}
