/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emprego.view;

import emprego.Banco;
import emprego.model.Profissional;
import emprego.model.Solicitacao;
import emprego.model.Usuario;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gcamargo
 */
public class FrameSolicitacao extends javax.swing.JFrame {

    List<Solicitacao> listaSolicitacao = new ArrayList<>();
    List<Profissional> listaprofissional = new ArrayList<>();
    Usuario usuariologado;
    Profissional profissional;
    int codigoProfissional;

    /**
     * Creates new form Solicitacao
     * @param usuario //Usuario logado (quem chamou o metodo)
     * @param listaprofissional //lista de Profissionais cadastrados
     * @param codigo //codigo do usuario logado (desnecessario)
     * @param listasolicitacao //Lista de Solicitacoes registradas no banco
     */
    public FrameSolicitacao(Usuario usuario, List<Profissional> listaprofissional, int codigo, List<Solicitacao> listasolicitacao) {
        initComponents();
        this.listaSolicitacao = listasolicitacao;
        this.listaprofissional = listaprofissional;
        this.usuariologado = usuario;
        this.codigoProfissional = codigo;
        Banco montarprofissional = new Banco();
        Profissional profissionall = montarprofissional.procuraProfissional(listaprofissional, codigoProfissional);
        this.profissional = profissionall;
        jLabelEmaildoProfissional.setText(profissional.getEmail());
        jLabelNomeProfissional.setText(profissional.getNome());
        jLabelTelefoneProfissional.setText(String.valueOf(profissional.getTelefone()));

    }

    /**
     *Construtor padrao
     */
    public FrameSolicitacao() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProfissional = new javax.swing.JLabel();
        jLabelNomeProfissional = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelEmaildoProfissional = new javax.swing.JLabel();
        jLabelDescreva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoServico = new javax.swing.JTextArea();
        jLabelMaxChar = new javax.swing.JLabel();
        jButtonSolicitar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelTelefoneProfissional = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelProfissional.setText("Profissional:");

        jLabelEmail.setText("Email:");

        jLabelDescreva.setText("Descreva o serviço: ");

        jTextAreaDescricaoServico.setColumns(20);
        jTextAreaDescricaoServico.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoServico);

        jLabelMaxChar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabelMaxChar.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMaxChar.setText("Máx. 144 Caracteres");

        jButtonSolicitar.setText("Solicitar");
        jButtonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelTelefone.setText("Telefone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelMaxChar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelEmail)
                                .addComponent(jLabelProfissional)
                                .addComponent(jLabelTelefone))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDescreva)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNomeProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEmaildoProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                                .addComponent(jLabelTelefoneProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProfissional)
                    .addComponent(jLabelNomeProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelEmaildoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelTelefoneProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabelDescreva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMaxChar)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSolicitar)
                    .addComponent(jButtonVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Inicio voltar = new Inicio(usuariologado);
        voltar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarActionPerformed
        try {
            Banco solicitar = new Banco();
            String descricao = jTextAreaDescricaoServico.getText();

            if (solicitar.contratarProfissional(codigoProfissional, descricao, usuariologado.getIdUsuario())) {
                JOptionPane.showMessageDialog(null, "Solicitação enviada, aguarde contato do profissional.");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível solicitar o serviço. Verifique sua conexão com o banco e tente Novamente.");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameSolicitacao.class.getName()).log(Level.SEVERE, null, "Verifique as configurações do Banco de dados.");
        }

    }//GEN-LAST:event_jButtonSolicitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSolicitacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSolicitar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelDescreva;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmaildoProfissional;
    private javax.swing.JLabel jLabelMaxChar;
    private javax.swing.JLabel jLabelNomeProfissional;
    private javax.swing.JLabel jLabelProfissional;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTelefoneProfissional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricaoServico;
    // End of variables declaration//GEN-END:variables
}
